### ISSUE TITLE
Creating new DAO does not wait anymore till it shows the "done screen"

### ISSUE THREAD

**Issue by H34D** [Conflux-Network-Global/aragon-client#10]
**Describe the bug**
When creating a new DAO the "your DAO has been created" screen is shown immediately even when the transaction has not been mined yet.

**Mainnet or testnet?**
Testnet

**Organization**
All

**To Reproduce**
1. Create new DAO

**Expected behavior**
see description

**Comment by Thegaram** [comment]
As I recall there's also a progress bar, and the UI should switch to the newly created DAO automatically, these two features do not work either.

**Comment by H34D** [comment]
the problem is that `await walletWeb3.eth.sendTransaction(transaction)` never resolves when being sent to the conflux portal

**Comment by H34D** [comment]
switched from await to callback, now it works again
