### ISSUE TITLE
Contract call reverts on V2 endpoint

### ISSUE THREAD

**Issue by H34D** [Conflux-Network-Global/aragon-client#11]
request: {“jsonrpc”:“2.0",“id”:14,“method”:“cfx_call”,“params”:[{“data”:“0xfd64eccb”,“to”:“cfxtest:acew78u5pgbbexxpmk79fgw95232c6my164xdrhthg”},“latest_state”]}

returns: {“jsonrpc”:“2.0",“error”:{“code”:-32015,“message”:“Transaction reverted”,“data”:“0x”},“id”:14}

**Comment by Thegaram** [comment]
`0xfd64eccb ` corresponds to the method `isForwarder()` (see [here](https://www.4byte.directory/signatures/?bytes4_signature=0xfd64eccb)). `cfxtest:acew78u5pgbbexxpmk79fgw95232c6my164xdrhthg` (`0x892efa1b6182124e6c527bf29A5Fde33817154bf` [[converter](https://testnet.confluxscan.io/address-converter)]) is the ACL of the DAO at `0x874d5E0541578bF7db45C2D46b2dD237F699E5ee`.

If you look in the aragonOS repo, ACL does not implement `IForwarder` that contains the `isForwarder` method. Only `Agent`, `TokenManager`, and `Voting` do. This method is used in aragon-wrapper like [this](https://github.com/Conflux-Network-Global/aragon.js/blob/3a334947a0042f5fa8812c13ce20646d8bcf03c4/packages/aragon-wrapper/src/index.js#L396). So revert seems expected to me in this case.

**Comment by H34D** [comment]
its working even with the errors closed
