### ISSUE TITLE
Should display all addresses in base32 format

### ISSUE THREAD

**Issue by Thegaram** [Conflux-Network-Global/aragon-client#15]
**Describe the bug**

When I switch to "Tokens", "Permissions" or "Organization", I still see the hex-addresses instead of the base32 ones (cfxtest:...).

**To Reproduce**
1. Open a DAO
2. Click on "Tokens"

**Expected behavior**

All addresses displayed should use the base32 format.

**Screenshots**

![image](https://user-images.githubusercontent.com/7571518/115811750-e3a4be00-a422-11eb-974c-b580235fadfd.png)

**Comment by H34D** [comment]
done
