### ISSUE TITLE
Unable to use base32 address in inputs

### ISSUE THREAD

**Issue by Thegaram** [Conflux-Network-Global/aragon-client#16]
**Describe the bug**

When I execute actions that take an address parameters (e.g. issue tokens) I should be able to use base32 addresses.

**To Reproduce**
1. Open a DAO
2. Go to "Tokens"
3. Click on "Add tokens"
4. Input a base32 address (`cfxtest:...`) and a number of tokens (e.g. 10)
5. Click on "Add tokens"
6. See error

**Expected behavior**

I expect to be able to input base32 addresses, e.g. copy my address from Portal and use it. Do not need to support hex addresses.

**Screenshots**

![image](https://user-images.githubusercontent.com/7571518/115811483-5eb9a480-a422-11eb-8fb6-72126bf2b9de.png)

**Comment by H34D** [comment]
done
