### ISSUE TITLE
Transaction is still "pending" even after it has been confirmed

### ISSUE THREAD

**Issue by Thegaram** [Conflux-Network-Global/aragon-client#17]
**Describe the bug**

When I submit a transaction (e.g. create a vote), I can follow its progress in the "Transaction activity" panel at the top right corner. However, it remains pending even after the transaction has been confirmed (based on a notification from Conflux Portal).

**To Reproduce**
1. Go to "Tokens"
2. Add a new token to a user
3. Confirm transaction in Portal
4. Click on the bell icon in the top right corner.

**Expected behavior**

The transaction status should change to confirmed/completed.

**Screenshots**

![image](https://user-images.githubusercontent.com/7571518/115812100-67f74100-a423-11eb-8fcd-560ed06ff2f8.png)

**Comment by Thegaram** [comment]
These logs might be relevant:

![image](https://user-images.githubusercontent.com/7571518/115813273-73e40280-a425-11eb-976a-f5ccabe44826.png)

Seems like the transaction hashes are stored in local storage and they're refreshed when the app is opened.

```
Failed to refresh transaction 0x148e515c2010d896a8f5b672f1bcfb819ac0c272e8315d36ad5b09dddae3e5a1: Error: Given address "CFXTEST:TYPE.USER:AAS55KS7F4MWWFF6SWYAEYJRB8W39HN0G2UMK5NB7Z" is not a valid Ethereum address.
```

**Comment by H34D** [comment]
using callback instead of await as well and it works
