### ISSUE TITLE
App states are not updated

### ISSUE THREAD

**Issue by Thegaram** [Conflux-Network-Global/aragon-client#20]
**Describe the bug**

It seems to me that the results of transaction are not reflected on the UI. For instance, when I submit a vote, it should show up under the "Voting" app, but it does not.

**To Reproduce**
1. Open a DAO
2. Go to "Voting"
3. Create a new vote
4. Wait for the transaction to be confirmed
5. Check the "Voting" app again

**Expected behavior**

New votes should show up.

**Screenshots**

After a while the apps stopped loading so I was unable to take a screenshot.

**Comment by H34D** [comment]
the unpacking of cfx_getTransactionByHash was not transforming the from and to addresses properly which lead to errors. this is fixed now
