### ISSUE TITLE
progress bar never succeeds even when the transaction succeeded

### ISSUE THREAD

**Issue by H34D** [Conflux-Network-Global/aragon-client#22]
<img width="363" alt="Screenshot 2021-04-27 at 14 24 01" src="https://user-images.githubusercontent.com/13647606/116241184-e8d87480-a764-11eb-83d6-e3fabbd111b0.png">
<img width="336" alt="Screenshot 2021-04-27 at 14 27 18" src="https://user-images.githubusercontent.com/13647606/116241187-e9710b00-a764-11eb-98fc-34eda25d521b.png">
<img width="341" alt="Screenshot 2021-04-27 at 14 36 56" src="https://user-images.githubusercontent.com/13647606/116242267-0bb75880-a766-11eb-83f5-367334569853.png">

**Comment by H34D** [comment]
closed for #17

**Comment by Thegaram** [comment]
It seems this is still not resolved. Just did a Deposit on the Finance app. The token showed up but even after minutes the transaction is still showed as pending.

![image](https://user-images.githubusercontent.com/7571518/117255669-7e1dec00-ae7c-11eb-824f-59f669f7caaf.png)

**Comment by jbesraa** [comment]
fixed @ 9ab3bc8ef2fe812e77bec4700662f948dab6ba10
