### ISSUE TITLE
how to deal with the delay between creating a DAO and fetching it from the indexing service?

### ISSUE THREAD

**Issue by H34D** [Conflux-Network-Global/aragon-client#24]
When creating DAOs and loading them afterwards there is a big delay between the indexing service and the blockchain data when trying to load it. How do you want this handled?

**Comment by H34D** [comment]
`yeah now it's keeping a safe distance from the tip of the ledger to avoid chain reorgs. we'll fix this to ensure there's no large delay. for now, if this is affecting your work, changing 'latest_confirmed' to 'latest_state' and snooze(10000) to snooze(1000) in event-indexer/src/events.js should solve this.`

**Comment by Thegaram** [comment]
For now, please see my comment in Slack. Let's keep this issue open so that I can make sure it gets addressed properly.

**Comment by H34D** [comment]
the delay is now so small that it might be ignored?

**Comment by H34D** [comment]
fixed by #38
