### ISSUE TITLE
Unable to deposit custom token

### ISSUE THREAD

**Issue by Thegaram** [Conflux-Network-Global/aragon-client#27]
When I specify the testnet FC token contract (`cfxtest:achkx35n7vngfxgrm7akemk3ftzy47t61yk5nn270s`) under Deposit in the Finance app, I see the following error:

![image](https://user-images.githubusercontent.com/7571518/117257226-3f893100-ae7e-11eb-8049-09958c8dfb29.png)

**Comment by H34D** [comment]
fixed
