### ISSUE TITLE
Some requests to indexer are aborted

### ISSUE THREAD

**Issue by Thegaram** [Conflux-Network-Global/aragon-client#28]
During recent testing I saw that some requests (but not all) to the indexer are aborted:

![image](https://user-images.githubusercontent.com/7571518/117392490-c2fd5d80-af24-11eb-9902-1bf155cc92f3.png)

![image](https://user-images.githubusercontent.com/7571518/117392357-803b8580-af24-11eb-9fe5-4b4549d6bd2e.png)

**Comment by H34D** [comment]
yes, it returns 520 on the preflight request
<img width="672" alt="Screenshot 2021-05-12 at 14 39 01" src="https://user-images.githubusercontent.com/13647606/118003447-e2432300-b348-11eb-9fd7-0ca357aedead.png">

**Comment by Thegaram** [comment]
It seems the issue was this: The indexing (sending `cfx_getLogs` queries to the Conflux node) prevented the server from serving the CORS preflight request. They were eventually served but I guess browsers use a short timeout for this request and simply displayed this timeout as 520 and CORS failure. Now I separated the indexer and the corresponding server into two separate processes and the issue seems to be gone.
