### ISSUE TITLE
Cannot read property 'cache' of null

### ISSUE THREAD

**Issue by Thegaram** [Conflux-Network-Global/aragon-client#34]
I see this on the latest version when I click "Clear application cache".

![image](https://user-images.githubusercontent.com/7571518/118077661-1f5df280-b3e7-11eb-9890-ecacb76ede07.png)

**Comment by jbesraa** [comment]
the wrapper object is null if a DAO is not selected, so the caching works probably in a dao level. I disabled the button when a dao is not selected

resolved here https://github.com/Conflux-Network-Global/aragon-client/commit/8416c2921a0ff6b457cf40efd32b72d843e4838e
