### ISSUE TITLE
Should disallow opening DAO before indexer is ready

### ISSUE THREAD

**Issue by Thegaram** [Conflux-Network-Global/aragon-client#38]
In my experience, it takes about 30 seconds for the indexer to collect logs after a DAO has been created. It would be nice to "grey out" this button and then enable it after about 30 seconds.

![image](https://user-images.githubusercontent.com/7571518/118110861-8397ab00-b415-11eb-8097-649661be8d8b.png)

**Comment by H34D** [comment]
done
